import os
import datetime
import json

# First check if API key exists, exit early if not
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY environment variable not set.")

# Only import and configure Gemini if API key is available and valid
try:
    import google.generativeai as genai
    
    # Test if the API key is valid by making a simple check
    if GEMINI_API_KEY and not GEMINI_API_KEY.startswith(('test', 'fake', 'dummy')) and len(GEMINI_API_KEY) > 20:
        genai.configure(api_key=GEMINI_API_KEY)
        generation_config = {
            "temperature": 0.7,
            "top_p": 0.95,  
            "top_k": 40,
            "max_output_tokens": 4096,
        }
        safety_settings = [
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
        ]

        # Use gemini-pro for text generation 
        text_model = genai.GenerativeModel(
            model_name="gemini-pro",
            generation_config=generation_config,
            safety_settings=safety_settings
        )
        API_AVAILABLE = True
        print("✅ Gemini API configured successfully")
    else:
        print("⚠️ Invalid or test API key detected, using fallback content")
        API_AVAILABLE = False
    
except Exception as e:
    print(f"⚠️ Warning: Could not configure Gemini API: {e}")
    API_AVAILABLE = False

# --- Date and Paths ---
now = datetime.datetime.now()
year = now.year
month = now.month
month_str = f"{month:02d}"

# Get the month name in Korean
month_names_kr = {
    1: "1월", 2: "2월", 3: "3월", 4: "4월", 5: "5월", 6: "6월",
    7: "7월", 8: "8월", 9: "9월", 10: "10월", 11: "11월", 12: "12월"
}
month_name_kr = month_names_kr[month]

article_dir = os.path.join(os.path.dirname(__file__), "articles")
os.makedirs(article_dir, exist_ok=True)

article_path = os.path.join(article_dir, f"{year}-{month_str}.html")
index_path = os.path.join(os.path.dirname(__file__), "index.html")

# --- Content Generation ---
def load_image_config():
    """Load image configuration from JSON file."""
    config_path = os.path.join(os.path.dirname(__file__), "image_config.json")
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print("⚠️ image_config.json not found, using placeholders only")
        return None
    except json.JSONDecodeError as e:
        print(f"⚠️ Error parsing image_config.json: {e}")
        return None

def create_image_element(description, index, image_url=None, image_type="ai_trend"):
    """Create an image element or placeholder based on availability."""
    if image_url:
        return f"""
        <div class="image-container" style="margin: 10px 0; text-align: center;">
            <img src="{image_url}" 
                 alt="{description}" 
                 style="max-width: 100%; height: 300px; object-fit: cover; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);"
                 onerror="this.onerror=null; this.style.display='none'; this.nextElementSibling.style.display='block';" />
            <div class="image-placeholder" style="display: none; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                 color: white; padding: 40px 20px; margin: 10px 0; text-align: center; border-radius: 8px;">
                <h4 style="margin: 0 0 10px 0;">🎨 이미지 로드 실패</h4>
                <p style="margin: 0; font-size: 14px; opacity: 0.9;">{description}</p>
                <small style="opacity: 0.7;">이미지 #{index + 1}</small>
            </div>
            <p style="margin: 10px 0 0 0; font-size: 12px; color: #666; font-style: italic;">{description}</p>
        </div>
        """
    else:
        # Fallback to original placeholder
        return create_image_placeholder(description, index)

def create_image_placeholder(description, index):
    """Create a placeholder for image that would be generated by an image AI service."""
    return f"""
    <div class="image-placeholder" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
         color: white; padding: 40px 20px; margin: 10px 0; text-align: center; border-radius: 8px;">
        <h4 style="margin: 0 0 10px 0;">🎨 AI 생성 이미지</h4>
        <p style="margin: 0; font-size: 14px; opacity: 0.9;">{description}</p>
        <small style="opacity: 0.7;">이미지 #{index + 1}</small>
    </div>
    """

def get_image_for_style(style_name, image_config, image_type="ai_generated_images"):
    """Get image URL for a specific style from configuration."""
    if not image_config:
        return None
    
    # Try exact match first
    if image_type in image_config and style_name in image_config[image_type]:
        return image_config[image_type][style_name]
    
    # Try partial match
    if image_type in image_config:
        for key, url in image_config[image_type].items():
            if key in style_name or style_name in key:
                return url
    
    # Return default image if available
    if "default_image" in image_config:
        if image_type == "ai_generated_images" and "ai_trend" in image_config["default_image"]:
            return image_config["default_image"]["ai_trend"]
        elif image_type == "celebrity_images" and "celebrity" in image_config["default_image"]:
            return image_config["default_image"]["celebrity"]
    
    return None

def generate_content_with_api(prompt, description):
    """Try to generate content with API, fall back to None if failed."""
    if not API_AVAILABLE:
        print(f"API not available, using fallback for {description}")
        return None
        
    try:
        print(f"Generating {description} using Gemini API...")
        response = text_model.generate_content(prompt)
        if response and response.text:
            print(f"{description} generated successfully")
            return response.text
        else:
            print(f"Empty response from API for {description}")
            return None
    except Exception as e:
        print(f"Error generating {description}: {e}")
        return None

def generate_html_content(year, month, month_name_kr):
    """Generates the HTML content for the article using Gemini API."""
    
    # Load image configuration
    image_config = load_image_config()
    
    # Generate main content using Gemini API
    main_prompt = f"""
    {year}년 {month_name_kr} 최신 헤어스타일 트렌드에 대한 상세한 블로그 글을 한국어로 작성해주세요.
    
    다음 내용을 포함해주세요:
    1. 이번 달의 주요 헤어스타일 트렌드 소개
    2. 각 트렌드의 특징과 어울리는 얼굴형
    3. 스타일링 팁과 추천 제품
    4. 계절에 맞는 헤어 관리법
    
    글은 친근하고 정보가 풍부한 톤으로 작성하고, 약 800-1000자 정도로 써주세요.
    """
    
    api_main_content = generate_content_with_api(main_prompt, "main content")
    main_content = api_main_content if api_main_content else f"""
    <div class="main-content">
        <h2>✨ {year}년 {month_name_kr} 헤어스타일 트렌드</h2>
        <p>이번 달은 다양한 헤어스타일이 주목받고 있습니다. 자연스러운 웨이브부터 볼드한 컷까지, 
        개성을 표현할 수 있는 다양한 옵션들이 트렌드를 이끌고 있어요.</p>
        
        <p>특히 레이어드 컷과 뱅 스타일이 인기를 끌고 있으며, 자연스러운 컬러링도 많은 사랑을 받고 있습니다. 
        계절에 맞는 헤어 케어와 함께 나만의 스타일을 찾아보세요!</p>
        
        <p>🌟 <strong>이번 달의 키워드:</strong> 자연스러움, 개성, 다양성</p>
        <p>💡 <strong>추천 스타일:</strong> 본인의 얼굴형과 라이프스타일에 맞는 스타일을 선택하여 
        전문가와 상담 후 시도해보시길 권합니다.</p>
    </div>
    """

    # Generate trend descriptions
    trend_prompt = f"""
    {year}년 {month_name_kr}의 인기 헤어스타일 10가지를 나열하고, 각각에 대해 간단한 설명(1-2문장)을 한국어로 작성해주세요.
    
    형식:
    1. 스타일명 - 설명
    2. 스타일명 - 설명
    ...
    
    다양한 길이와 스타일을 포함해주세요 (숏컷, 미디엄, 롱 등).
    """
    
    api_trend_text = generate_content_with_api(trend_prompt, "trend descriptions")
    if api_trend_text:
        trend_descriptions = [desc.strip() for desc in api_trend_text.split('\n') if desc.strip()][:10]
    else:
        trend_descriptions = [
            "1. 레이어드 밥 - 자연스러운 층을 만든 밥 컷으로 볼륨감을 살린 스타일",
            "2. 커튼 뱅 - 가운데 가르마를 중심으로 양쪽으로 자연스럽게 떨어지는 앞머리",
            "3. 울프 컷 - 멀릿과 셰그를 결합한 레트로한 분위기의 헤어스타일",
            "4. 픽시 컷 - 짧고 단정한 컷으로 세련되고 시크한 느낌",
            "5. 롱 레이어 - 긴 머리에 층을 넣어 움직임과 볼륨을 살린 스타일",
            "6. 셰그 컷 - 불규칙한 레이어로 자연스럽고 무디한 느낌의 헤어",
            "7. 프렌치 밥 - 클래식한 밥 컷에 프렌치 시크함을 더한 스타일",
            "8. 비치 웨이브 - 자연스러운 파도 같은 웨이브로 휴양지 느낌",
            "9. 블런트 컷 - 끝선이 일직선으로 정리된 깔끔한 스타일",
            "10. 하이브리드 컷 - 여러 스타일을 믹스한 개성 있는 헤어스타일"
        ]

    # Generate celebrity trends
    celebrity_prompt = f"""
    {year}년 {month_name_kr}에 한국 연예인들 사이에서 인기인 헤어스타일 10가지를 나열하고, 
    각각에 대해 간단한 설명을 한국어로 작성해주세요.
    
    형식:
    1. 스타일명 - 어떤 연예인 스타일인지와 특징 설명
    2. 스타일명 - 어떤 연예인 스타일인지와 특징 설명
    ...
    """
    
    api_celebrity_text = generate_content_with_api(celebrity_prompt, "celebrity descriptions")
    if api_celebrity_text:
        celebrity_descriptions = [desc.strip() for desc in api_celebrity_text.split('\n') if desc.strip()][:10]
    else:
        celebrity_descriptions = [
            "1. 아이유 스타일 시스루 뱅 - 가벼운 앞머리로 여성스럽고 청순한 이미지",
            "2. 태연 스타일 웨이브 밥 - 어깨선 밥 컷에 자연스러운 웨이브",
            "3. 블랙핑크 제니 스타일 - 시크한 블런트 밥으로 강렬한 인상",
            "4. 수지 스타일 긴 생머리 - 건강하고 윤기 나는 긴 스트레이트 헤어",
            "5. 전지현 스타일 롱 컬 - 글래머러스한 긴 컬 헤어",
            "6. 송혜교 스타일 미디엄 웨이브 - 우아하고 성숙한 느낌의 웨이브",
            "7. 박신혜 스타일 레이어드 컷 - 자연스러운 층으로 볼륨감 있는 스타일",
            "8. 한소희 스타일 울프 컷 - 트렌디하고 개성 있는 울프 컷",
            "9. 김고은 스타일 숏 밥 - 깔끔하고 모던한 느낌의 짧은 밥",
            "10. 김태리 스타일 픽시 컷 - 개성 강한 베리 숏 헤어스타일"
        ]

    # Create HTML structure with improved styling
    html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{year}년 {month_name_kr} 최신트랜드</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            background-color: #f8f9fa;
            color: #333;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
            font-weight: 300;
        }}
        .content {{
            padding: 30px;
        }}
        .section {{
            margin-bottom: 40px;
        }}
        .section h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        .trend-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }}
        .trend-item {{
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            overflow: hidden;
            transition: transform 0.3s ease;
        }}
        .trend-item:hover {{
            transform: translateY(-2px);
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }}
        .trend-content {{
            padding: 15px;
        }}
        .back-link {{
            display: inline-block;
            margin-top: 30px;
            padding: 10px 20px;
            background-color: #667eea;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }}
        .back-link:hover {{
            background-color: #5a6fd8;
        }}
        @media (max-width: 768px) {{
            body {{ padding: 10px; }}
            .header {{ padding: 30px 20px; }}
            .header h1 {{ font-size: 2em; }}
            .content {{ padding: 20px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{year}년 {month_name_kr} 최신트랜드</h1>
            <p>이번 달의 헤어스타일 트렌드를 확인해보세요! ✨</p>
        </div>
        
        <div class="content">
            <div class="section">
                {main_content}
            </div>
            
            <div class="section">
                <h2>🔥 최신 헤어스타일 트렌드 (10선)</h2>
                <div class="trend-grid">
                    {''.join([f'''
                    <div class="trend-item">
                        {create_image_element(f"트렌드 헤어스타일: {desc.split(' - ')[0] if ' - ' in desc else desc[:20]}", i, get_image_for_style(desc.split(' - ')[0] if ' - ' in desc else desc.split('.')[1].strip() if '.' in desc else desc[:20], image_config, "ai_generated_images"), "ai_trend")}
                        <div class="trend-content">
                            <p><strong>{desc}</strong></p>
                        </div>
                    </div>
                    ''' for i, desc in enumerate(trend_descriptions)])}
                </div>
            </div>
            
            <div class="section">
                <h2>⭐ 연예계 최신 헤어스타일</h2>
                <div class="trend-grid">
                    {''.join([f'''
                    <div class="trend-item">
                        {create_image_element(f"연예인 헤어스타일: {desc.split(' - ')[0] if ' - ' in desc else desc[:20]}", i, get_image_for_style(desc.split(' - ')[0] if ' - ' in desc else desc.split('.')[1].strip() if '.' in desc else desc[:20], image_config, "celebrity_images"), "celebrity")}
                        <div class="trend-content">
                            <p><strong>{desc}</strong></p>
                        </div>
                    </div>
                    ''' for i, desc in enumerate(celebrity_descriptions)])}
                </div>
            </div>
            
            <a href="../index.html" class="back-link">← 메인으로 돌아가기</a>
        </div>
    </div>
</body>
</html>"""
    return html

# --- File Operations ---
def update_index_file(year, month, month_name_kr):
    """Updates the index.html file with a link to the new article."""
    new_link = f'        <li><a href="articles/{year}-{month:02d}.html">{year}년 {month_name_kr}</a></li>'
    
    try:
        with open(index_path, "r", encoding='utf-8') as f:
            content = f.read()
        
        # Check if link already exists
        if f'{year}-{month:02d}.html' in content:
            print(f"Link for {year}년 {month_name_kr} already exists in index.html")
            return
            
        # Add the new link before the placeholder comment
        if "<!-- Links to monthly articles will be added here -->" in content:
            content = content.replace(
                "<!-- Links to monthly articles will be added here -->", 
                f"{new_link}\n        <!-- Links to monthly articles will be added here -->"
            )
        else:
            # If placeholder doesn't exist, add before closing </ul>
            content = content.replace("</ul>", f"    {new_link}\n    </ul>")
        
        with open(index_path, "w", encoding='utf-8') as f:
            f.write(content)
            
        print(f"Added link for {year}년 {month_name_kr} to index.html")
        
    except Exception as e:
        print(f"Error updating index file: {e}")

# --- Main Execution ---
if __name__ == "__main__":
    print(f"Generating monthly hairstyle trend article for {year}년 {month_name_kr}...")
    
    try:
        html_content = generate_html_content(year, month, month_name_kr)
        with open(article_path, "w", encoding='utf-8') as f:
            f.write(html_content)
        print(f"Article created at {article_path}")

        update_index_file(year, month, month_name_kr)
        print(f"Index file updated at {index_path}")
        print("✅ Successfully generated monthly hairstyle trend article!")
        
    except Exception as e:
        print(f"❌ Error generating article: {e}")
        raise
